### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by longlho** [ljharb/es-abstract#110]
Any particular reason why this repo doesn't provide type definition natively?

**Comment by ljharb** [comment]
Because it's not authored in TypeScript. It's a very bad idea for non-TS packages to ship first-class types, because there's no practical way to ensure that the definitions don't deviate from the actual thing that matters, the JS implementation.

Please feel free to PR any type improvements into DefinitelyTyped; I'll be tagged as a reviewer there.
